[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[context.production.environment]
  NODE_VERSION = "18"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
